/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validate/rut": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate Rut Endpoint */
        get: operations["validate_rut_endpoint_api_v1_validate_rut_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_auth_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set User Role */
        post: operations["set_user_role_api_v1_auth_users__user_id__role_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proveedores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proveedores */
        get: operations["list_proveedores_api_v1_proveedores_get"];
        put?: never;
        /** Create Proveedor */
        post: operations["create_proveedor_api_v1_proveedores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proveedores/{proveedor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proveedor */
        get: operations["get_proveedor_api_v1_proveedores__proveedor_id__get"];
        put?: never;
        post?: never;
        /** Delete Proveedor */
        delete: operations["delete_proveedor_api_v1_proveedores__proveedor_id__delete"];
        options?: never;
        head?: never;
        /** Update Proveedor */
        patch: operations["update_proveedor_api_v1_proveedores__proveedor_id__patch"];
        trace?: never;
    };
    "/api/v1/catalogos/empresas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Empresas
         * @description Catálogo plano de empresas activas — único source-of-truth para selects (Disciplina 1).
         */
        get: operations["list_empresas_api_v1_catalogos_empresas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Catalogos */
        get: operations["get_catalogos_api_v1_catalogos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kpis */
        get: operations["get_kpis_api_v1_dashboard_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/cashflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cashflow
         * @description Devuelve los últimos N meses pivotando real vs proyectado.
         *
         *     Si `empresa_codigo` es None, agrega sobre todo el portafolio.
         */
        get: operations["get_cashflow_api_v1_dashboard_cashflow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/egresos-por-concepto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Egresos Por Concepto
         * @description Top 10 conceptos por egreso del periodo. Default: periodo actual.
         */
        get: operations["get_egresos_por_concepto_api_v1_dashboard_egresos_por_concepto_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/saldos-por-empresa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Saldos Por Empresa
         * @description Saldo actual + variación últimos 30 días por empresa.
         */
        get: operations["get_saldos_por_empresa_api_v1_dashboard_saldos_por_empresa_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/iva-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Iva Trend */
        get: operations["get_iva_trend_api_v1_dashboard_iva_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/proyectos-ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proyectos Ranking */
        get: operations["get_proyectos_ranking_api_v1_dashboard_proyectos_ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/movimientos-recientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Movimientos Recientes */
        get: operations["get_movimientos_recientes_api_v1_dashboard_movimientos_recientes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ordenes-compra": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ocs */
        get: operations["list_ocs_api_v1_ordenes_compra_get"];
        put?: never;
        /** Create Oc */
        post: operations["create_oc_api_v1_ordenes_compra_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ordenes-compra/{oc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Oc */
        get: operations["get_oc_api_v1_ordenes_compra__oc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ordenes-compra/{oc_id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Estado */
        patch: operations["update_estado_api_v1_ordenes_compra__oc_id__estado_patch"];
        trace?: never;
    };
    "/api/v1/movimientos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Movimientos */
        get: operations["list_movimientos_api_v1_movimientos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/f29": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List F29 */
        get: operations["list_f29_api_v1_f29_get"];
        put?: never;
        /** Create F29 */
        post: operations["create_f29_api_v1_f29_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/f29/{f29_id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update F29 Estado */
        patch: operations["update_f29_estado_api_v1_f29__f29_id__estado_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CashflowPoint */
        CashflowPoint: {
            /** Periodo */
            periodo: string;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /** Abono Real */
            abono_real: string;
            /** Egreso Real */
            egreso_real: string;
            /** Abono Proyectado */
            abono_proyectado: string;
            /** Egreso Proyectado */
            egreso_proyectado: string;
            /** Flujo Neto Real */
            flujo_neto_real: string;
            /** Flujo Neto Proyectado */
            flujo_neto_proyectado: string;
            /** Saldo Acumulado */
            saldo_acumulado: string;
        };
        /** CashflowResponse */
        CashflowResponse: {
            /** Empresa Codigo */
            empresa_codigo: string | null;
            /** Points */
            points: components["schemas"]["CashflowPoint"][];
        };
        /** CatalogosResponse */
        CatalogosResponse: {
            /** Empresas */
            empresas: {
                [key: string]: string | null;
            }[];
            /** Concepto General */
            concepto_general: string[];
            /** Concepto Detallado */
            concepto_detallado: components["schemas"]["ConceptoDetallado"][];
            /** Tipo Egreso */
            tipo_egreso: string[];
            /** Fuente */
            fuente: string[];
            /** Proyecto */
            proyecto: string[];
            /** Banco */
            banco: string[];
        };
        /** ConceptoDetallado */
        ConceptoDetallado: {
            /** Concepto Detallado */
            concepto_detallado: string;
            /** Concepto General */
            concepto_general: string | null;
        };
        /**
         * DashboardKPIs
         * @description Hero stats del dashboard. Todo lo necesario para 6 tarjetas grandes.
         */
        DashboardKPIs: {
            /** Saldo Total Consolidado */
            saldo_total_consolidado: string;
            /** Saldo Total Cehta */
            saldo_total_cehta: string;
            /** Saldo Total Corfo */
            saldo_total_corfo: string;
            /** Egreso Mes Actual */
            egreso_mes_actual: string;
            /** Egreso Mes Anterior */
            egreso_mes_anterior: string;
            /** Egreso Delta Pct */
            egreso_delta_pct: number;
            /** Abono Mes Actual */
            abono_mes_actual: string;
            /** Abono Mes Anterior */
            abono_mes_anterior: string;
            /** Abono Delta Pct */
            abono_delta_pct: number;
            /** Flujo Neto Mes */
            flujo_neto_mes: string;
            /** Iva A Pagar Mes */
            iva_a_pagar_mes: string;
            /** Oc Emitidas Pendientes */
            oc_emitidas_pendientes: number;
            /** Monto Oc Pendiente */
            monto_oc_pendiente: string;
            /** F29 Proximas 30D */
            f29_proximas_30d: number;
            /** F29 Vencidas */
            f29_vencidas: number;
            /** Ultimo Etl Run */
            ultimo_etl_run: string | null;
            /** Etl Status */
            etl_status: string;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Saldos Por Empresa */
            saldos_por_empresa: components["schemas"]["SaldoEmpresa"][];
            /** Movimientos Recientes */
            movimientos_recientes: components["schemas"]["MovimientoReciente"][];
            oc_resumen: components["schemas"]["OCResumen"];
            /** F29 Pendientes */
            f29_pendientes: components["schemas"]["F29Resumen"][];
            /** Periodo Actual */
            periodo_actual: string;
        };
        /** EgresoConcepto */
        EgresoConcepto: {
            /** Concepto General */
            concepto_general: string;
            /** Concepto Detallado */
            concepto_detallado: string | null;
            /** Total Egreso */
            total_egreso: string;
            /** Porcentaje */
            porcentaje: number;
            /** Num Movimientos */
            num_movimientos: number;
        };
        /** EmpresaCatalogo */
        EmpresaCatalogo: {
            /** Codigo */
            codigo: string;
            /** Razon Social */
            razon_social: string;
            /** Oc Prefix */
            oc_prefix?: string | null;
            /** Rut */
            rut?: string | null;
        };
        /** EstadoUpdateRequest */
        EstadoUpdateRequest: {
            /**
             * Estado
             * @enum {string}
             */
            estado: "emitida" | "pagada" | "anulada" | "parcial";
        };
        /** F29Create */
        F29Create: {
            /** Empresa Codigo */
            empresa_codigo: string;
            /** Periodo Tributario */
            periodo_tributario: string;
            /**
             * Fecha Vencimiento
             * Format: date
             */
            fecha_vencimiento: string;
            /** Monto A Pagar */
            monto_a_pagar?: number | string | null;
            /**
             * Estado
             * @default pendiente
             * @enum {string}
             */
            estado: "pendiente" | "pagado" | "vencido" | "exento";
        };
        /** F29EstadoUpdate */
        F29EstadoUpdate: {
            /**
             * Estado
             * @enum {string}
             */
            estado: "pendiente" | "pagado" | "vencido" | "exento";
            /** Fecha Pago */
            fecha_pago?: string | null;
            /** Comprobante Url */
            comprobante_url?: string | null;
        };
        /** F29Read */
        F29Read: {
            /** F29 Id */
            f29_id: number;
            /** Empresa Codigo */
            empresa_codigo: string;
            /** Periodo Tributario */
            periodo_tributario: string;
            /**
             * Fecha Vencimiento
             * Format: date
             */
            fecha_vencimiento: string;
            /** Monto A Pagar */
            monto_a_pagar: string | null;
            /** Fecha Pago */
            fecha_pago: string | null;
            /** Estado */
            estado: string;
            /** Comprobante Url */
            comprobante_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** F29Resumen */
        F29Resumen: {
            /** Empresa Codigo */
            empresa_codigo: string;
            /** Periodo Tributario */
            periodo_tributario: string;
            /** Fecha Vencimiento */
            fecha_vencimiento: string;
            /** Monto A Pagar */
            monto_a_pagar: string | null;
            /** Estado */
            estado: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /** IvaPoint */
        IvaPoint: {
            /** Periodo */
            periodo: string;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /** Iva Credito */
            iva_credito: string;
            /** Iva Debito */
            iva_debito: string;
            /** Iva A Pagar */
            iva_a_pagar: string;
        };
        /** MovimientoRead */
        MovimientoRead: {
            /** Movimiento Id */
            movimiento_id: number;
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Descripcion */
            descripcion: string | null;
            /** Abono */
            abono: string;
            /** Egreso */
            egreso: string;
            /** Saldo Contable */
            saldo_contable: string | null;
            /** Saldo Cehta */
            saldo_cehta: string | null;
            /** Saldo Corfo */
            saldo_corfo: string | null;
            /** Concepto General */
            concepto_general: string | null;
            /** Concepto Detallado */
            concepto_detallado: string | null;
            /** Tipo Egreso */
            tipo_egreso: string | null;
            /** Fuente */
            fuente: string | null;
            /** Proyecto */
            proyecto: string | null;
            /** Banco */
            banco: string | null;
            /** Real Proyectado */
            real_proyectado: string | null;
            /** Anio */
            anio: number;
            /** Periodo */
            periodo: string;
            /** Empresa Codigo */
            empresa_codigo: string;
            /** Iva Credito Fiscal */
            iva_credito_fiscal: string;
            /** Iva Debito Fiscal */
            iva_debito_fiscal: string;
            /** Tipo Documento */
            tipo_documento: string | null;
            /** Numero Documento */
            numero_documento: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MovimientoReciente */
        MovimientoReciente: {
            /** Movimiento Id */
            movimiento_id: number;
            /** Fecha */
            fecha: string;
            /** Empresa Codigo */
            empresa_codigo: string;
            /** Descripcion */
            descripcion: string | null;
            /** Abono */
            abono: string;
            /** Egreso */
            egreso: string;
            /** Concepto General */
            concepto_general: string | null;
            /** Proyecto */
            proyecto: string | null;
        };
        /** OCDetalleCreate */
        OCDetalleCreate: {
            /** Item */
            item: number;
            /** Descripcion */
            descripcion: string;
            /** Precio Unitario */
            precio_unitario: number | string;
            /** Cantidad */
            cantidad: number | string;
        };
        /** OCDetalleRead */
        OCDetalleRead: {
            /** Detalle Id */
            detalle_id: number;
            /** Item */
            item: number;
            /** Descripcion */
            descripcion: string;
            /** Precio Unitario */
            precio_unitario: string;
            /** Cantidad */
            cantidad: string;
            /** Total Linea */
            total_linea: string | null;
        };
        /** OCResumen */
        OCResumen: {
            /** Total Emitidas */
            total_emitidas: number;
            /** Monto Total Emitidas */
            monto_total_emitidas: string;
            /** Total Pagadas */
            total_pagadas: number;
            /** Monto Total Pagadas */
            monto_total_pagadas: string;
            /** Total Anuladas */
            total_anuladas: number;
        };
        /** OrdenCompraCreate */
        OrdenCompraCreate: {
            /** Numero Oc */
            numero_oc: string;
            /** Empresa Codigo */
            empresa_codigo: string;
            /** Proveedor Id */
            proveedor_id?: number | null;
            /**
             * Fecha Emision
             * Format: date
             */
            fecha_emision: string;
            /**
             * Validez Dias
             * @default 30
             */
            validez_dias: number;
            /**
             * Moneda
             * @default CLP
             * @enum {string}
             */
            moneda: "CLP" | "UF" | "USD";
            /** Neto */
            neto: number | string;
            /** Forma Pago */
            forma_pago?: string | null;
            /** Plazo Pago */
            plazo_pago?: string | null;
            /** Observaciones */
            observaciones?: string | null;
            /** Items */
            items: components["schemas"]["OCDetalleCreate"][];
        };
        /** OrdenCompraListItem */
        OrdenCompraListItem: {
            /** Oc Id */
            oc_id: number;
            /** Numero Oc */
            numero_oc: string;
            /** Empresa Codigo */
            empresa_codigo: string;
            /** Proveedor Id */
            proveedor_id: number | null;
            /**
             * Fecha Emision
             * Format: date
             */
            fecha_emision: string;
            /** Moneda */
            moneda: string;
            /** Neto */
            neto: string;
            /** Total */
            total: string;
            /** Estado */
            estado: string;
            /** Pdf Url */
            pdf_url: string | null;
            /**
             * Allowed Actions
             * @default []
             */
            allowed_actions: string[];
        };
        /** OrdenCompraRead */
        OrdenCompraRead: {
            /** Oc Id */
            oc_id: number;
            /** Numero Oc */
            numero_oc: string;
            /** Empresa Codigo */
            empresa_codigo: string;
            /** Proveedor Id */
            proveedor_id: number | null;
            /**
             * Fecha Emision
             * Format: date
             */
            fecha_emision: string;
            /** Validez Dias */
            validez_dias: number;
            /** Moneda */
            moneda: string;
            /** Neto */
            neto: string;
            /** Iva */
            iva: string;
            /** Total */
            total: string;
            /** Forma Pago */
            forma_pago: string | null;
            /** Plazo Pago */
            plazo_pago: string | null;
            /** Observaciones */
            observaciones: string | null;
            /** Estado */
            estado: string;
            /** Pdf Url */
            pdf_url: string | null;
            /** Items */
            items: components["schemas"]["OCDetalleRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Allowed Actions
             * @default []
             */
            allowed_actions: string[];
        };
        /** Page[F29Read] */
        Page_F29Read_: {
            /** Items */
            items: components["schemas"]["F29Read"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[MovimientoRead] */
        Page_MovimientoRead_: {
            /** Items */
            items: components["schemas"]["MovimientoRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[OrdenCompraListItem] */
        Page_OrdenCompraListItem_: {
            /** Items */
            items: components["schemas"]["OrdenCompraListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[ProveedorRead] */
        Page_ProveedorRead_: {
            /** Items */
            items: components["schemas"]["ProveedorRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** ProveedorCreate */
        ProveedorCreate: {
            /** Razon Social */
            razon_social: string;
            /** Rut */
            rut?: string | null;
            /** Giro */
            giro?: string | null;
            /** Direccion */
            direccion?: string | null;
            /** Ciudad */
            ciudad?: string | null;
            /** Contacto */
            contacto?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Email */
            email?: string | null;
            /** Banco */
            banco?: string | null;
            /** Tipo Cuenta */
            tipo_cuenta?: string | null;
            /** Numero Cuenta */
            numero_cuenta?: string | null;
        };
        /** ProveedorRead */
        ProveedorRead: {
            /** Razon Social */
            razon_social: string;
            /** Rut */
            rut?: string | null;
            /** Giro */
            giro?: string | null;
            /** Direccion */
            direccion?: string | null;
            /** Ciudad */
            ciudad?: string | null;
            /** Contacto */
            contacto?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Email */
            email?: string | null;
            /** Banco */
            banco?: string | null;
            /** Tipo Cuenta */
            tipo_cuenta?: string | null;
            /** Numero Cuenta */
            numero_cuenta?: string | null;
            /** Proveedor Id */
            proveedor_id: number;
            /** Activo */
            activo: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProveedorUpdate */
        ProveedorUpdate: {
            /** Razon Social */
            razon_social?: string | null;
            /** Rut */
            rut?: string | null;
            /** Giro */
            giro?: string | null;
            /** Direccion */
            direccion?: string | null;
            /** Ciudad */
            ciudad?: string | null;
            /** Contacto */
            contacto?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Email */
            email?: string | null;
            /** Banco */
            banco?: string | null;
            /** Tipo Cuenta */
            tipo_cuenta?: string | null;
            /** Numero Cuenta */
            numero_cuenta?: string | null;
        };
        /** ProyectoRanking */
        ProyectoRanking: {
            /** Proyecto */
            proyecto: string;
            /** Total Egreso */
            total_egreso: string;
            /** Num Movimientos */
            num_movimientos: number;
            /** Empresas */
            empresas: string[];
        };
        /** RutValidationResponse */
        RutValidationResponse: {
            /** Valid */
            valid: boolean;
            /** Formatted */
            formatted: string | null;
            /** Message */
            message: string | null;
        };
        /** SaldoEmpresa */
        SaldoEmpresa: {
            /** Empresa Codigo */
            empresa_codigo: string;
            /** Razon Social */
            razon_social: string;
            /** Saldo Cehta */
            saldo_cehta: string | null;
            /** Saldo Corfo */
            saldo_corfo: string | null;
            /** Saldo Contable */
            saldo_contable: string | null;
            /** Periodo */
            periodo: string | null;
        };
        /** SaldoEmpresaDetalle */
        SaldoEmpresaDetalle: {
            /** Empresa Codigo */
            empresa_codigo: string;
            /** Razon Social */
            razon_social: string;
            /** Saldo Contable */
            saldo_contable: string | null;
            /** Saldo Cehta */
            saldo_cehta: string | null;
            /** Saldo Corfo */
            saldo_corfo: string | null;
            /** Ultima Actualizacion */
            ultima_actualizacion: string | null;
            /** Delta 30D */
            delta_30d: string;
        };
        /** SetRoleRequest */
        SetRoleRequest: {
            /** App Role */
            app_role: string;
        };
        /** UserMeResponse */
        UserMeResponse: {
            /** Sub */
            sub: string;
            /** Email */
            email: string | null;
            /** App Role */
            app_role: string;
            /** Allowed Actions */
            allowed_actions: string[];
        };
        /** UserRoleItem */
        UserRoleItem: {
            /** User Id */
            user_id: string;
            /** App Role */
            app_role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    validate_rut_endpoint_api_v1_validate_rut_get: {
        parameters: {
            query: {
                /** @description RUT con o sin formato: '12.345.678-9' o '123456789' */
                rut: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RutValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_auth_users_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRoleItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_role_api_v1_auth_users__user_id__role_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proveedores_api_v1_proveedores_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                search?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProveedorRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_proveedor_api_v1_proveedores_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProveedorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProveedorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proveedor_api_v1_proveedores__proveedor_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                proveedor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProveedorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_proveedor_api_v1_proveedores__proveedor_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                proveedor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_proveedor_api_v1_proveedores__proveedor_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                proveedor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProveedorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProveedorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_empresas_api_v1_catalogos_empresas_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaCatalogo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catalogos_api_v1_catalogos_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogosResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kpis_api_v1_dashboard_kpis_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardKPIs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cashflow_api_v1_dashboard_cashflow_get: {
        parameters: {
            query?: {
                empresa_codigo?: string | null;
                meses?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_egresos_por_concepto_api_v1_dashboard_egresos_por_concepto_get: {
        parameters: {
            query?: {
                empresa_codigo?: string | null;
                periodo?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EgresoConcepto"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_saldos_por_empresa_api_v1_dashboard_saldos_por_empresa_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaldoEmpresaDetalle"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_iva_trend_api_v1_dashboard_iva_trend_get: {
        parameters: {
            query?: {
                empresa_codigo?: string | null;
                meses?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IvaPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proyectos_ranking_api_v1_dashboard_proyectos_ranking_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProyectoRanking"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_movimientos_recientes_api_v1_dashboard_movimientos_recientes_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovimientoReciente"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ocs_api_v1_ordenes_compra_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                empresa_codigo?: string | null;
                estado?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OrdenCompraListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_oc_api_v1_ordenes_compra_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrdenCompraCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdenCompraRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_oc_api_v1_ordenes_compra__oc_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                oc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdenCompraRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_estado_api_v1_ordenes_compra__oc_id__estado_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                oc_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstadoUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdenCompraRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_movimientos_api_v1_movimientos_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                empresa_codigo?: string | null;
                anio?: number | null;
                periodo?: string | null;
                real_proyectado?: string | null;
                proyecto?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MovimientoRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_f29_api_v1_f29_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                empresa_codigo?: string | null;
                estado?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_F29Read_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_f29_api_v1_f29_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["F29Create"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["F29Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_f29_estado_api_v1_f29__f29_id__estado_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                f29_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["F29EstadoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["F29Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
